# Generated by Django 5.0 on 2024-01-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='catagory',
            field=models.CharField(default='Others', max_length=255),
        ),
    ]
